config/routes.rb
Rails.application.routes.draw do

  constraints ->  request { request.session[:user_id].present? } do
    # ログインしてる時のパス
    root  "posts#index"
  end
  # ログインしてない時のパス
  root  "static_pages#home"

  get '/users/show',   to: "users#show"
  get "/users/edit",   to: "users#edit"
  get "/signup",       to: "users#new"
  post "/signup",      to: "users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    resources :photos, only: [:create]
    resources :comments, only: [:index, :create, :destroy], shallow: true

  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <nav>
    <ul>
      <li><%= link_to "<写真をアップロード>",   '/posts/new', class: "btn btn-primary" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Instaboon", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
        <li><%= link_to "ユーザー一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              検索 <b class="caret"></b>
            </a>
　            <ul class="dropdown-menu">
　              <p>投稿を検索する</p>
                  <%= form_tag root_path, :method => 'get' do %>
                <p>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "検索", :name => nil %>
                </p>
                  <% end %>
              </ul>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>